name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # version is set with package.json "packageManager" field

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: "package.json"

      - name: Install dependencies
        run: pnpm install

      # Looks like maintaining (restoring and saving updated cache) nextjs cache takes close to 1 minute (24s to restore and 40'ish to save off).
      # If your nextjs build is shorter than that then there is no benefit here
      # - name: Cache Next.js build
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build and Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_SCHEMA: "todo"
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_DISABLE_SIGN_UPS: "true"
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          AUTH_TRUST_HOST: "true"
          PRODUCTION_URL: "https://todo.illizen.com"
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          pnpm build:packages
